CI:
    - .github/**
CMake:
    - "**CMakeLists.txt"
    - cmake/**
OpenGL:
    - src/contour/opengl/*.cpp
    - src/contour/opengl/*.h
"VT: backend":
    - src/vtbackend/*.cpp
    - src/vtbackend/*.h
    - src/vtpty/*.cpp
    - src/vtpty/*.h
    - src/vtparser/*.cpp
    - src/vtparser/*.h
"VT: rasterizer":
    - src/vtrasterizer/*.cpp
    - src/vtrasterizer/*.h
documentation:
    - "**/*.md"
    - docs/**
fonts:
    - src/text_shaper/*.cpp
    - src/text_shaper/*.h
frontend:
    - src/contour/**
test:
    - src/**/*_test.cpp
